apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-volume
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 100M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce