version: '1.0'
services:
  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - '6379:6379'
  web:
      build: .
      container_name: web
      env_file: .env
      ports:
          - "5000:5000"
      volumes:
          - .:/code
      depends_on:
          - redis
networks:
  defult:
    driver: custom-driver-1
